export class Station {
  // uuid: string;
  // industry: string;
  name: string;
  pcb: string;
  // realtime_url: string;
  // delayed_url: string;
  prefix: string;
  version: string;
  address: string;
  zipcode: number;
  longitude: string;
  latitude: string;
  state: string;
  city: string;
  country: string;
  user_email: string;
  user_ph: string;
  // notify_cpcb: boolean;
  // cpcb_email: string;
  // cpcb_ph: string;
  seasonal_offline: boolean;
  site_status: string;
  // closure_status: string;
  monitoring_type: string;
  process_attached: string;
  ganga_basin: boolean;
  approval_date: string;
  // is_allowed: boolean;
  created: string;
  camera: string;
  // calibration: boolean;
}
